---
build_from:
  aarch64: ghcr.io/hassio-addons/base:13.1.0
  amd64: ghcr.io/hassio-addons/base:13.1.0
  armhf: ghcr.io/hassio-addons/base:13.1.0
  armv7: ghcr.io/hassio-addons/base:13.1.0
  i386: ghcr.io/hassio-addons/base:13.1.0
args:
  TEMPIO_VERSION: "2021.09.0"