build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
#codenotary:
#  signer: "nicfragale+cas@gmail.com"
#  base_image: "notary@home-assistant.io"
