build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:stable"
  amd64: "ghcr.io/hassio-addons/base/amd64:stable"
  armv7: "ghcr.io/hassio-addons/base/armv7:stable"
args:
  CLIVERSION: ""
  ZTVERSION: "1.1.3"
  ZTBRANCHOVERRIDE: ""
codenotary:
  signer: "nicfragale+cas@gmail.com"
#  base_image: "notary@home-assistant.io"