build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:16.2.0"
  amd64: "ghcr.io/hassio-addons/base/amd64:16.2.0"
  armv7: "ghcr.io/hassio-addons/base/armv7:16.2.0"
args:
  CLIVERSION: ""
  ZTVERSION: "1.1.0"
  ZTBRANCHOVERRIDE: ""
codenotary:
  signer: "nicfragale+cas@gmail.com"
#  base_image: "notary@home-assistant.io"