build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:15.0.7"
  amd64: "ghcr.io/hassio-addons/base/amd64:15.0.7"
  armv7: "ghcr.io/hassio-addons/base/armv7:15.0.7"
args:
  CLIVERSION: ""
  ZTVERSION: "0.22.3"
  ZTBRANCHOVERRIDE: ""
codenotary:
  signer: "nicfragale+cas@gmail.com"
#  base_image: "notary@home-assistant.io"