name: "NetFoundry OpenZITI"
description: "NetFoundry OpenZITI - Zero Trust Application Specific Networking"
version: "1.0.0"
slug: "openziti"
url: "https://github.com/openziti"
startup: services
init: false
panel_icon: mdi:lightning-bolt-circle
panel_title: NetFoundry OpenZITI
arch:
  - aarch64
#  - amd64
#  - armhf
#  - armv7
#  - i386
hassio_api: true
hassio_role: manager
auth_api: true
host_dbus: true
host_network: true
network_mode: host
host_ipc: true
map:
  - share:rw
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
#volumes:
#  - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
options:
  EnrollmentJWT: "UNSET"
  IdentityDirectory: "DEFAULT"
  LogLevel: "DEFAULT"
  UpstreamResolver: "DEFAULT"
  ResolutionRange: "100.64.64.0/18"
schema:
  EnrollmentJWT: str?
  IdentityDirectory: str?
  LogLevel: list(1|2|DEFAULT|4|5|6)?
  UpstreamResolver: str?
  ResolutionRange: list(100.64.0.0/18|100.64.64.0/18)?
